In [5]:
import numpy as np

<center><h2 style="color:white">
<hr>
Creating a numpy array<hr></h2></center>

In [33]:
# creating a numpy array

array1D=np.array([1,2,3,4,5,5],dtype=np.int16")
print(array1D)
type(array1D)

[1 2 3 4 5 5]


numpy.ndarray

In [34]:
array1D.itemsize

2

In [36]:
array1D.dtype

dtype('int16')

In [41]:
array2D = np.array([[1,2,3,4,5,7],[1,2,3,4,5,7]],dtype=np.int16)
print(array2D)

[[1 2 3 4 5 7]
 [1 2 3 4 5 7]]


In [42]:
array2D.ndim

2

In [43]:
array2D.shape

(2, 6)

In [68]:
#  using arange fnc

arr = np.arange(10,20)
brr =arr.reshape(2,5)  # reshape creates a shallow copy of the original array

In [69]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [70]:
brr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [108]:
crr = np.linspace(11,20,60).reshape(3,4,5)
crr

AttributeError: 'tuple' object has no attribute 'reshape'

In [117]:
drr = np.linspace(11,20,1000000,retstep=True)
drr

(array([11.      , 11.000009, 11.000018, ..., 19.999982, 19.999991,
        20.      ]),
 9.000009000009e-06)

In [127]:
crr.reshape(3,4,5)
crr.shape

(3, 4, 5)

In [130]:
drr=np.zeros((3,5)
drr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<center><h2 style="color:white">
<hr>
Array traversal<hr></h2></center>

In [150]:
arr= np.array([[1,2,3],[4,5,8],[7,8,9]])

In [151]:
for i in arr:
    print(i)

[1 2 3]
[4 5 8]
[7 8 9]


In [153]:
for i in crr:
    print("-----------------------------------")
    print("           ITERATION               ")
    print("-----------------------------------")
    print(i[2,3])

-----------------------------------
           ITERATION               
-----------------------------------
12.983050847457626
-----------------------------------
           ITERATION               
-----------------------------------
16.033898305084747
-----------------------------------
           ITERATION               
-----------------------------------
19.084745762711865


In [156]:
for i in crr:
    print("-----------------------------------")
    print("           ITERATION               ")
    print("-----------------------------------")
    for j in i :
        for k in j:
            print(k)

-----------------------------------
           ITERATION               
-----------------------------------
11.0
11.152542372881356
11.305084745762711
11.457627118644067
11.610169491525424
11.76271186440678
11.915254237288135
12.067796610169491
12.220338983050848
12.372881355932204
12.525423728813559
12.677966101694915
12.830508474576272
12.983050847457626
13.135593220338983
13.288135593220339
13.440677966101696
13.593220338983052
13.745762711864407
13.898305084745763
-----------------------------------
           ITERATION               
-----------------------------------
14.05084745762712
14.203389830508474
14.35593220338983
14.508474576271187
14.661016949152543
14.813559322033898
14.966101694915254
15.11864406779661
15.271186440677965
15.423728813559322
15.576271186440678
15.728813559322035
15.881355932203391
16.033898305084747
16.186440677966104
16.338983050847457
16.491525423728813
16.64406779661017
16.796610169491526
16.949152542372882
-----------------------------------
       

<center><h2 style="color:white">
<hr>
Vector Operations<hr></h2></center>

In [158]:
# methods available in maths are also available in numpy

<center><h2 style="color:white">
<hr>
Statistical Array <hr></h2></center>

In [180]:
a = np.array([[1,2,4,5,6,1],[2,3,1,2,3,7]])
print(a.argmin(axis=1))   # return the index of the minimum element

[0 2]


In [182]:
a.flatten()

array([1, 2, 4, 5, 6, 1, 2, 3, 1, 2, 3, 7])

In [211]:
np.random.randint(3,5,(1,15))

array([[4, 3, 3, 4, 4, 3, 3, 4, 3, 4, 3, 4, 3, 4, 3]])

In [219]:
np.eye(4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])